import './globals.css'
import { Inter } from 'next/font/google'
import { AuthContextProvider } from '../context/AuthContext'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className +' h-screen bg-bg flex flex-col justify-between min-h-full pb-6  '}>
      <AuthContextProvider>
        <Navbar />
          {children}
        <Footer />
      </AuthContextProvider>
      </body>
    </html>
  )
}
